# -*- coding: utf-8 -*-
"""genaitask-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVjrvM6WY1GQfgmXfJYgp49Eu2SnDDzD

**Install Required Libraries**
"""

!pip install diffusers transformers accelerate scipy safetensors

"""**Import and Load the Model**"""

from diffusers import StableDiffusionPipeline
import torch

# Load pipeline (requires Hugging Face token if private)
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")  # Use 'cpu' if no GPU

"""**Generate Image from Text**"""

from IPython.display import display

prompt = "A futuristic city at sunset, with flying cars"
image = pipe(prompt).images[0]

display(image)

"""**Generate Image from Text**"""

prompt = "A medieval castle on a mountain during sunrise"
image = pipe(prompt).images[0]

display(image)

"""**Generate Image from Text**"""

prompt = "A man enjoying sunset with his family"
image = pipe(prompt).images[0]

display(image)

"""**Generate Image from Text**"""

prompt = "A detailed painting of the Taj Mahal at sunrise"
image = pipe(prompt).images[0]

display(image)